$schemaver: 2.0
repo_url: https://github.com/byu-oit/awslogin
software:
  - aliases:
    assignment_group: 'gro:AD-Global Education Initiative'
    ddd:
      business_domain:
      context_map_url:
      ubiquitous_language_url:
    developed_by_byu: true
    links:
      swagger_urls:
      system_documentation_url: https://github.com/byu-oit/awslogin
    maintained_by:
      - dsw88
      - pauldeden
    microservice: false
    name: awslogin
    notes:
    short_description: 'Script for CLI access to AWS via ADFS'
    stages:
      development:
        aws_account:
        hosting_location: Other
        relationships:
          depends_on:
            db_read_only:
            db_read_write:
            software:
          reverse_proxy:
          runs_on:
            blade_server:
            rack_server:
            server_cluster:
            virtual_server:
          supports:
            service:
            software:
        urls:
          physical_url:
          product_page:
          virtual_url:
    standard_change_template_id:
    tags:
      app: awslogin
      data-sensitivity: confidential
      team: 'gro:AD-Global Education Initiative'
    technologies_used:
      - Python
      - 'AWS CodeBuild'
    type: 'command-line app'
